import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  he: {
    // General
    appName: "מערכת ניהול תורים",
    login: "התחברות",
    logout: "התנתקות",
    register: "הרשמה",
    email: "אימייל",
    password: "סיסמה",
    phone: "טלפון",
    submit: "שלח",
    cancel: "ביטול",
    save: "שמור",
    delete: "מחק",
    edit: "ערוך",
    loading: "טוען...",
    search: "חיפוש",
    back: "חזרה",
    next: "הבא",
    previous: "הקודם",
    
    // Login
    loginWithPassword: "התחברות עם סיסמה",
    loginWithOTP: "התחברות עם קוד חד פעמי",
    nationalId: "תעודת זהות",
    sendOTP: "שלח קוד",
    enterOTP: "הזן קוד שנשלח לאימייל",
    noAccount: "אין לך חשבון?",
    forgotPassword: "שכחת סיסמה?",
    
    // Patient
    myCalendar: "היומן שלי",
    myAppointments: "התורים שלי",
    myReferrals: "ההפניות שלי",
    bookAppointment: "קביעת תור",
    pregnancyWeek: "שבוע הריון",
    upcomingAppointments: "תורים קרובים",
    noAppointments: "אין תורים קרובים",
    referralValid: "הפניה בתוקף",
    referralExpired: "הפניה פגה תוקף",
    scheduleNow: "קבע תור עכשיו",
    availabilityAlert: "התראת זמינות",
    requestAlert: "בקש התראה כשיתפנה מקום",
    cannotReschedule: "לא ניתן לשנות תור פחות מ-7 ימים לפני. אנא התקשר למזכירות.",
    
    // Secretary
    dashboard: "לוח בקרה",
    followUpList: "רשימת מעקב",
    allAppointments: "כל התורים",
    manageSlots: "ניהול משבצות",
    uploadReferral: "העלאת הפניה",
    patientsWithoutAppointment: "מטופלים ללא תור",
    daysWithoutScheduling: "ימים ללא קביעת תור",
    markAttendance: "סמן נוכחות",
    attended: "הגיע",
    notAttended: "לא הגיע",
    
    // Calendar
    today: "היום",
    week: "שבוע",
    month: "חודש",
    
    // Days
    sunday: "ראשון",
    monday: "שני",
    tuesday: "שלישי",
    wednesday: "רביעי",
    thursday: "חמישי",
    friday: "שישי",
    saturday: "שבת",
    
    // Additional translations
    patient: "מטופל",
    doctor: "רופא",
    location: "מיקום",
    date: "תאריך",
    time: "שעה",
    duration: "משך",
    minutes: "דקות",
    addSlot: "הוסף משבצת",
    noSlotsForDay: "אין משבצות ליום זה",
    confirmBooking: "אשר תור",
    backToDashboard: "חזרה ללוח הבקרה",
    selectPatient: "בחר מטופל",
    searchByNameOrId: "חיפוש לפי שם או ת.ז",
    noPatientsFound: "לא נמצאו מטופלים",
    addPatient: "הוסף מטופל",
    managePatients: "ניהול מטופלים",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    dateOfBirth: "תאריך לידה",
    pregnancyStartDate: "תאריך תחילת הריון",
    preferredLanguage: "שפה מועדפת",
    editPatient: "עריכת פרטי מטופל",
    addNewPatient: "הוספת מטופל חדש",
    todaysSummary: "סיכום היום",
    noAppointmentsToday: "אין תורים היום",
    quickActions: "פעולות מהירות",
    from: "משעה",
    until: "עד שעה",
    saveAlert: "שמור התראה",
    myAlerts: "ההתראות שלי",
    noActiveAlerts: "אין התראות פעילות",
    allDoctors: "כל הרופאים",
    anyDoctor: "כל רופא",
    optional: "אופציונלי",
    required: "שדה חובה",
    fillAllRequired: "נא למלא את כל השדות הנדרשים",
    referralAddedSuccess: "ההפניה נוספה בהצלחה",
    patientWillBeNotified: "המטופל יקבל התראה לקביעת תור",
    addAnother: "הוסף הפניה נוספת",
    addNewReferral: "הוספת הפניה חדשה",
    referringDoctor: "רופא מפנה",
    nameOfReferringDoctor: "שם הרופא המפנה",
    referralDate: "תאריך הפניה",
    validUntil: "תוקף עד",
    attachReferralFile: "צרף קובץ הפניה",
    clickToUpload: "לחץ להעלאת קובץ",
    remove: "הסר",
    notes: "הערות",
    additionalNotes: "הערות נוספות",
    saveReferral: "שמור הפניה",
    appointmentBookedFor: "התור נקבע עבור",
    change: "שנה",
    site: "מיקום",
    selectSite: "בחר מיקום",
    startTime: "שעת התחלה",
    durationMin: "משך (דקות)",
    availabilityAlerts: "התראות זמינות",
    getNotifiedWhen: "קבל התראה כאשר תור מתפנה בזמנים המועדפים עליך",
    addNewAlert: "הוסף התראה חדשה",
    specificDate: "תאריך ספציפי",
    alertSaved: "ההתראה נשמרה",
    alertRemoved: "ההתראה הוסרה",
    detailsUpdated: "הפרטים עודכנו",
    patientAddedSuccess: "המטופל נוסף בהצלחה",
    name: "שם",
    language: "שפה",
    id: "ת.ז",
    actions: "פעולות",
    todaysAppointments: "תורים היום",
    pendingApprovals: "ממתינים לאישור",
    confirmedToday: "מאושרים היום",
    followUp: "מעקב",
    patientsList: "רשימת מטופלים",
    appointmentsList: "רשימת תורים",
    
    // Status
    pending: "ממתין",
    confirmed: "מאושר",
    completed: "הושלם",
    cancelled: "בוטל",
    noShow: "לא הגיע",
    
    // Notifications
    newReferralTitle: "הפניה חדשה",
    newReferralMessage: "קיבלת הפניה חדשה. אנא קבע תור.",
    reminderTitle: "תזכורת",
    reminderMessage: "טרם קבעת תור להפניה שלך.",
    slotAvailable: "התפנה מקום",
    slotAvailableMessage: "משבצת זמן שביקשת התפנתה.",
    
    // Misc
    selectDoctor: "בחר רופא",
    selectDate: "בחר תאריך",
    selectTime: "בחר שעה",
    selectService: "בחר שירות",
    noAvailableSlots: "אין משבצות זמינות",
    appointmentBooked: "התור נקבע בהצלחה",
    selectLanguage: "בחר שפה",
  },
  ar: {
    appName: "نظام إدارة المواعيد",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    register: "تسجيل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    phone: "الهاتف",
    submit: "إرسال",
    cancel: "إلغاء",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    loading: "جاري التحميل...",
    search: "بحث",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    
    loginWithPassword: "تسجيل الدخول بكلمة المرور",
    loginWithOTP: "تسجيل الدخول برمز لمرة واحدة",
    nationalId: "رقم الهوية",
    sendOTP: "إرسال الرمز",
    enterOTP: "أدخل الرمز المرسل للبريد",
    noAccount: "ليس لديك حساب؟",
    forgotPassword: "نسيت كلمة المرور؟",
    
    myCalendar: "التقويم الخاص بي",
    myAppointments: "مواعيدي",
    myReferrals: "إحالاتي",
    bookAppointment: "حجز موعد",
    pregnancyWeek: "أسبوع الحمل",
    upcomingAppointments: "المواعيد القادمة",
    noAppointments: "لا توجد مواعيد قادمة",
    referralValid: "الإحالة صالحة",
    referralExpired: "الإحالة منتهية",
    scheduleNow: "احجز موعد الآن",
    availabilityAlert: "تنبيه التوفر",
    requestAlert: "طلب تنبيه عند توفر موعد",
    cannotReschedule: "لا يمكن تغيير الموعد قبل 7 أيام. يرجى الاتصال بالسكرتارية.",
    
    dashboard: "لوحة التحكم",
    followUpList: "قائمة المتابعة",
    allAppointments: "جميع المواعيد",
    manageSlots: "إدارة الفترات",
    uploadReferral: "رفع إحالة",
    patientsWithoutAppointment: "مرضى بدون موعد",
    daysWithoutScheduling: "أيام بدون حجز",
    markAttendance: "تسجيل الحضور",
    attended: "حضر",
    notAttended: "لم يحضر",
    
    today: "اليوم",
    week: "أسبوع",
    month: "شهر",
    
    sunday: "الأحد",
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    
    // Additional translations
    patient: "مريض",
    doctor: "طبيب",
    location: "موقع",
    date: "تاريخ",
    time: "وقت",
    duration: "مدة",
    minutes: "دقائق",
    addSlot: "إضافة فترة",
    noSlotsForDay: "لا توجد فترات لهذا اليوم",
    confirmBooking: "تأكيد الحجز",
    backToDashboard: "العودة إلى لوحة التحكم",
    selectPatient: "اختر المريض",
    searchByNameOrId: "بحث بالاسم أو الرقم",
    noPatientsFound: "لم يتم العثور على مرضى",
    addPatient: "إضافة مريض",
    managePatients: "إدارة المرضى",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    dateOfBirth: "تاريخ الميلاد",
    pregnancyStartDate: "تاريخ بدء الحمل",
    preferredLanguage: "اللغة المفضلة",
    editPatient: "تعديل بيانات المريض",
    addNewPatient: "إضافة مريض جديد",
    todaysSummary: "ملخص اليوم",
    noAppointmentsToday: "لا مواعيد اليوم",
    quickActions: "إجراءات سريعة",
    from: "من",
    until: "حتى",
    saveAlert: "حفظ التنبيه",
    myAlerts: "تنبيهاتي",
    noActiveAlerts: "لا توجد تنبيهات نشطة",
    allDoctors: "جميع الأطباء",
    anyDoctor: "أي طبيب",
    optional: "اختياري",
    required: "مطلوب",
    fillAllRequired: "يرجى ملء جميع الحقول المطلوبة",
    referralAddedSuccess: "تمت إضافة الإحالة بنجاح",
    patientWillBeNotified: "سيتلقى المريض إشعاراً لحجز موعد",
    addAnother: "إضافة أخرى",
    addNewReferral: "إضافة إحالة جديدة",
    referringDoctor: "الطبيب المحيل",
    nameOfReferringDoctor: "اسم الطبيب المحيل",
    referralDate: "تاريخ الإحالة",
    validUntil: "صالح حتى",
    attachReferralFile: "إرفاق ملف الإحالة",
    clickToUpload: "انقر للتحميل",
    remove: "إزالة",
    notes: "ملاحظات",
    additionalNotes: "ملاحظات إضافية",
    saveReferral: "حفظ الإحالة",
    appointmentBookedFor: "تم حجز الموعد لـ",
    change: "تغيير",
    site: "الموقع",
    selectSite: "اختر الموقع",
    startTime: "وقت البدء",
    durationMin: "المدة (دقائق)",
    availabilityAlerts: "تنبيهات التوفر",
    getNotifiedWhen: "احصل على إشعار عندما يتوفر موعد في الأوقات التي تفضلها",
    addNewAlert: "إضافة تنبيه جديد",
    specificDate: "تاريخ محدد",
    alertSaved: "تم حفظ التنبيه",
    alertRemoved: "تم إزالة التنبيه",
    detailsUpdated: "تم تحديث التفاصيل",
    patientAddedSuccess: "تمت إضافة المريض بنجاح",
    name: "الاسم",
    language: "اللغة",
    id: "الرقم",
    actions: "الإجراءات",
    todaysAppointments: "مواعيد اليوم",
    pendingApprovals: "بانتظار الموافقة",
    confirmedToday: "مؤكد اليوم",
    followUp: "متابعة",
    patientsList: "قائمة المرضى",
    appointmentsList: "قائمة المواعيد",
    
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    completed: "مكتمل",
    cancelled: "ملغى",
    noShow: "لم يحضر",
    
    newReferralTitle: "إحالة جديدة",
    newReferralMessage: "لديك إحالة جديدة. يرجى حجز موعد.",
    reminderTitle: "تذكير",
    reminderMessage: "لم تحجز موعداً لإحالتك بعد.",
    slotAvailable: "موعد متاح",
    slotAvailableMessage: "الفترة الزمنية التي طلبتها أصبحت متاحة.",
    
    selectDoctor: "اختر الطبيب",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    selectService: "اختر الخدمة",
    noAvailableSlots: "لا توجد فترات متاحة",
    appointmentBooked: "تم حجز الموعد بنجاح",
    selectLanguage: "اختر اللغة",
  },
  en: {
    appName: "Appointment Management System",
    login: "Login",
    logout: "Logout",
    register: "Register",
    email: "Email",
    password: "Password",
    phone: "Phone",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    loading: "Loading...",
    search: "Search",
    back: "Back",
    next: "Next",
    previous: "Previous",
    
    loginWithPassword: "Login with Password",
    loginWithOTP: "Login with OTP",
    nationalId: "National ID",
    sendOTP: "Send OTP",
    enterOTP: "Enter code sent to email",
    noAccount: "Don't have an account?",
    forgotPassword: "Forgot password?",
    
    myCalendar: "My Calendar",
    myAppointments: "My Appointments",
    myReferrals: "My Referrals",
    bookAppointment: "Book Appointment",
    pregnancyWeek: "Pregnancy Week",
    upcomingAppointments: "Upcoming Appointments",
    noAppointments: "No upcoming appointments",
    referralValid: "Referral Valid",
    referralExpired: "Referral Expired",
    scheduleNow: "Schedule Now",
    availabilityAlert: "Availability Alert",
    requestAlert: "Request alert when slot opens",
    cannotReschedule: "Cannot reschedule less than 7 days before. Please call the secretary.",
    
    dashboard: "Dashboard",
    followUpList: "Follow-up List",
    allAppointments: "All Appointments",
    manageSlots: "Manage Slots",
    uploadReferral: "Upload Referral",
    patientsWithoutAppointment: "Patients without appointment",
    daysWithoutScheduling: "Days without scheduling",
    markAttendance: "Mark Attendance",
    attended: "Attended",
    notAttended: "Not Attended",
    
    today: "Today",
    week: "Week",
    month: "Month",
    
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    
    // Additional translations
    patient: "Patient",
    doctor: "Doctor",
    location: "Location",
    date: "Date",
    time: "Time",
    duration: "Duration",
    minutes: "Minutes",
    addSlot: "Add Slot",
    noSlotsForDay: "No slots for this day",
    confirmBooking: "Confirm Booking",
    backToDashboard: "Back to Dashboard",
    selectPatient: "Select Patient",
    searchByNameOrId: "Search by name or ID",
    noPatientsFound: "No patients found",
    addPatient: "Add Patient",
    managePatients: "Manage Patients",
    firstName: "First Name",
    lastName: "Last Name",
    dateOfBirth: "Date of Birth",
    pregnancyStartDate: "Pregnancy Start Date",
    preferredLanguage: "Preferred Language",
    editPatient: "Edit Patient",
    addNewPatient: "Add New Patient",
    todaysSummary: "Today's Summary",
    noAppointmentsToday: "No appointments today",
    quickActions: "Quick Actions",
    from: "From",
    until: "Until",
    saveAlert: "Save Alert",
    myAlerts: "My Alerts",
    noActiveAlerts: "No active alerts",
    allDoctors: "All Doctors",
    anyDoctor: "Any Doctor",
    optional: "Optional",
    required: "Required",
    fillAllRequired: "Please fill all required fields",
    referralAddedSuccess: "Referral added successfully",
    patientWillBeNotified: "Patient will be notified to schedule appointment",
    addAnother: "Add Another",
    addNewReferral: "Add New Referral",
    referringDoctor: "Referring Doctor",
    nameOfReferringDoctor: "Name of referring doctor",
    referralDate: "Referral Date",
    validUntil: "Valid Until",
    attachReferralFile: "Attach Referral File",
    clickToUpload: "Click to upload file",
    remove: "Remove",
    notes: "Notes",
    additionalNotes: "Additional notes",
    saveReferral: "Save Referral",
    appointmentBookedFor: "Appointment booked for",
    change: "Change",
    site: "Site",
    selectSite: "Select site",
    startTime: "Start Time",
    durationMin: "Duration (min)",
    availabilityAlerts: "Availability Alerts",
    getNotifiedWhen: "Get notified when an appointment becomes available at your preferred times",
    addNewAlert: "Add New Alert",
    specificDate: "Specific Date",
    alertSaved: "Alert saved",
    alertRemoved: "Alert removed",
    detailsUpdated: "Details updated",
    patientAddedSuccess: "Patient added successfully",
    name: "Name",
    language: "Language",
    id: "ID",
    actions: "Actions",
    todaysAppointments: "Today's Appointments",
    pendingApprovals: "Pending Approvals",
    confirmedToday: "Confirmed Today",
    followUp: "Follow-up",
    patientsList: "Patients List",
    appointmentsList: "Appointments List",
    
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No Show",
    
    newReferralTitle: "New Referral",
    newReferralMessage: "You have a new referral. Please schedule an appointment.",
    reminderTitle: "Reminder",
    reminderMessage: "You haven't scheduled an appointment for your referral yet.",
    slotAvailable: "Slot Available",
    slotAvailableMessage: "A time slot you requested is now available.",
    
    selectDoctor: "Select Doctor",
    selectDate: "Select Date",
    selectTime: "Select Time",
    selectService: "Select Service",
    noAvailableSlots: "No available slots",
    appointmentBooked: "Appointment booked successfully",
    selectLanguage: "Select Language",
  },
  ru: {
    appName: "Система управления записями",
    login: "Вход",
    logout: "Выход",
    register: "Регистрация",
    email: "Электронная почта",
    password: "Пароль",
    phone: "Телефон",
    submit: "Отправить",
    cancel: "Отмена",
    save: "Сохранить",
    delete: "Удалить",
    edit: "Редактировать",
    loading: "Загрузка...",
    search: "Поиск",
    back: "Назад",
    next: "Далее",
    previous: "Предыдущий",
    
    loginWithPassword: "Вход с паролем",
    loginWithOTP: "Вход по коду",
    nationalId: "Удостоверение личности",
    sendOTP: "Отправить код",
    enterOTP: "Введите код из письма",
    noAccount: "Нет аккаунта?",
    forgotPassword: "Забыли пароль?",
    
    myCalendar: "Мой календарь",
    myAppointments: "Мои записи",
    myReferrals: "Мои направления",
    bookAppointment: "Записаться",
    pregnancyWeek: "Неделя беременности",
    upcomingAppointments: "Предстоящие записи",
    noAppointments: "Нет предстоящих записей",
    referralValid: "Направление действительно",
    referralExpired: "Направление истекло",
    scheduleNow: "Записаться сейчас",
    availabilityAlert: "Уведомление о доступности",
    requestAlert: "Запросить уведомление при освобождении",
    cannotReschedule: "Нельзя изменить запись менее чем за 7 дней. Позвоните в секретариат.",
    
    dashboard: "Панель управления",
    followUpList: "Список отслеживания",
    allAppointments: "Все записи",
    manageSlots: "Управление слотами",
    uploadReferral: "Загрузить направление",
    patientsWithoutAppointment: "Пациенты без записи",
    daysWithoutScheduling: "Дней без записи",
    markAttendance: "Отметить посещение",
    attended: "Присутствовал",
    notAttended: "Не присутствовал",
    
    today: "Сегодня",
    week: "Неделя",
    month: "Месяц",
    
    sunday: "Воскресенье",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    
    // Additional translations
    patient: "Пациент",
    doctor: "Врач",
    location: "Место",
    date: "Дата",
    time: "Время",
    duration: "Длительность",
    minutes: "Минуты",
    addSlot: "Добавить слот",
    noSlotsForDay: "Нет слотов на этот день",
    confirmBooking: "Подтвердить запись",
    backToDashboard: "Назад к панели",
    selectPatient: "Выберите пациента",
    searchByNameOrId: "Поиск по имени или ID",
    noPatientsFound: "Пациенты не найдены",
    addPatient: "Добавить пациента",
    managePatients: "Управление пациентами",
    firstName: "Имя",
    lastName: "Фамилия",
    dateOfBirth: "Дата рождения",
    pregnancyStartDate: "Дата начала беременности",
    preferredLanguage: "Предпочитаемый язык",
    editPatient: "Редактировать пациента",
    addNewPatient: "Добавить нового пациента",
    todaysSummary: "Сводка за сегодня",
    noAppointmentsToday: "Сегодня нет записей",
    quickActions: "Быстрые действия",
    from: "С",
    until: "До",
    saveAlert: "Сохранить уведомление",
    myAlerts: "Мои уведомления",
    noActiveAlerts: "Нет активных уведомлений",
    allDoctors: "Все врачи",
    anyDoctor: "Любой врач",
    optional: "Необязательно",
    required: "Обязательно",
    fillAllRequired: "Заполните все обязательные поля",
    referralAddedSuccess: "Направление успешно добавлено",
    patientWillBeNotified: "Пациент получит уведомление о записи",
    addAnother: "Добавить еще",
    addNewReferral: "Добавить новое направление",
    referringDoctor: "Направивший врач",
    nameOfReferringDoctor: "Имя направившего врача",
    referralDate: "Дата направления",
    validUntil: "Действительно до",
    attachReferralFile: "Прикрепить файл направления",
    clickToUpload: "Нажмите для загрузки",
    remove: "Удалить",
    notes: "Примечания",
    additionalNotes: "Дополнительные примечания",
    saveReferral: "Сохранить направление",
    appointmentBookedFor: "Запись создана для",
    change: "Изменить",
    site: "Место",
    selectSite: "Выберите место",
    startTime: "Время начала",
    durationMin: "Длительность (мин)",
    availabilityAlerts: "Уведомления о доступности",
    getNotifiedWhen: "Получайте уведомления когда появляется запись в удобное время",
    addNewAlert: "Добавить новое уведомление",
    specificDate: "Конкретная дата",
    alertSaved: "Уведомление сохранено",
    alertRemoved: "Уведомление удалено",
    detailsUpdated: "Данные обновлены",
    patientAddedSuccess: "Пациент успешно добавлен",
    name: "Имя",
    language: "Язык",
    id: "ID",
    actions: "Действия",
    todaysAppointments: "Записи на сегодня",
    pendingApprovals: "Ожидают подтверждения",
    confirmedToday: "Подтверждено сегодня",
    followUp: "Отслеживание",
    patientsList: "Список пациентов",
    appointmentsList: "Список записей",
    
    pending: "Ожидает",
    confirmed: "Подтверждено",
    completed: "Завершено",
    cancelled: "Отменено",
    noShow: "Не явился",
    
    newReferralTitle: "Новое направление",
    newReferralMessage: "У вас новое направление. Пожалуйста, запишитесь.",
    reminderTitle: "Напоминание",
    reminderMessage: "Вы еще не записались по направлению.",
    slotAvailable: "Слот доступен",
    slotAvailableMessage: "Запрошенное время стало доступно.",
    
    selectDoctor: "Выберите врача",
    selectDate: "Выберите дату",
    selectTime: "Выберите время",
    selectService: "Выберите услугу",
    noAvailableSlots: "Нет доступных слотов",
    appointmentBooked: "Запись успешно создана",
    selectLanguage: "Выберите язык",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'he';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.dir = ['he', 'ar'].includes(language) ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = ['he', 'ar'].includes(language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export default LanguageContext;
